import type { Issue, SolveResult } from "../engine/types.js";
import type { GitHubClient } from "./client.js";
import { log } from "../utils/logger.js";

/** Build a well-formatted PR body */
export function buildPRBody(
  issue: Issue,
  result: SolveResult,
  diffSummary: string
): string {
  const confidenceEmoji =
    result.confidence >= 8 ? "🟢" :
    result.confidence >= 5 ? "🟡" :
    "🔴";

  let body = `## ⚡ Solved by Dispatch\n\n`;
  body += `**Issue:** #${issue.number} — ${issue.title}\n`;
  body += `**Confidence:** ${confidenceEmoji} ${result.confidence}/10\n`;
  body += `**Type:** ${issue.classification || "unknown"}\n\n`;

  body += `### Summary\n\n${result.summary}\n\n`;

  if (result.uncertainties.length > 0) {
    body += `### ⚠️ Areas of Uncertainty\n\n`;
    for (const u of result.uncertainties) {
      body += `- ${u}\n`;
    }
    body += `\n`;
  }

  if (result.changedFiles.length > 0) {
    body += `### Changed Files\n\n`;
    for (const f of result.changedFiles) {
      body += `- \`${f}\`\n`;
    }
    body += `\n`;
  }

  if (diffSummary) {
    body += `### Diff Stats\n\n\`\`\`\n${diffSummary}\n\`\`\`\n\n`;
  }

  body += `---\n`;
  body += `Closes #${issue.number}\n\n`;
  body += `> 🤖 This PR was automatically generated by [Dispatch](https://github.com/nomadicmehul/dispatch).\n`;
  body += `> Review carefully before merging.`;

  return body;
}

/** Create a PR for a solved issue */
export async function createPRForIssue(
  client: GitHubClient,
  issue: Issue,
  result: SolveResult,
  options: {
    branchName: string;
    baseBranch: string;
    diffSummary: string;
    draft: boolean;
  }
): Promise<{ number: number; url: string }> {
  const body = buildPRBody(issue, result, options.diffSummary);

  // Build a concise PR title from the commit message:
  // - Use only the first line (subject line) of the commit message
  // - Truncate to 72 chars max (GitHub convention) after the prefix
  const firstLine = result.commitMessage.split("\n")[0].trim();
  const maxLen = 72 - "[dispatch] ".length; // ~61 chars for the message
  const truncated = firstLine.length > maxLen
    ? firstLine.substring(0, maxLen - 1).trimEnd() + "…"
    : firstLine;
  const prTitle = `[dispatch] ${truncated}`;

  const labels: string[] = ["dispatch"];
  if (result.confidence < 5) {
    labels.push("needs-review");
  }
  if (issue.classification) {
    labels.push(`type:${issue.classification}`);
  }

  const pr = await client.createPullRequest({
    title: prTitle,
    body,
    head: options.branchName,
    base: options.baseBranch,
    draft: options.draft || result.confidence < 5,
    labels,
  });

  log.success(`PR #${pr.number} created: ${pr.url}`);
  return pr;
}
