import { Command } from "commander";
import chalk from "chalk";
import { writeFile, mkdir, access } from "node:fs/promises";
import { join } from "node:path";
import { getRepoInfo } from "../utils/git.js";
import { log } from "../utils/logger.js";

const WORKFLOW_TEMPLATE = (cronSchedule: string, maxIssues: number, draft: boolean, labels: string[]) => `# Dispatch — Nightly Issue Solver
# Automatically solves open GitHub issues and creates pull requests.
# Generated by: dispatch schedule

name: Dispatch Nightly Run

on:
  schedule:
    # Runs at ${cronSchedule} UTC — adjust to your preferred time
    - cron: "${cronSchedule}"
  workflow_dispatch:
    # Allow manual trigger from GitHub Actions UI
    inputs:
      dry_run:
        description: "Dry run (preview only, no PRs)"
        required: false
        default: "false"
        type: boolean
      max_issues:
        description: "Max issues to process"
        required: false
        default: "${maxIssues}"
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  dispatch:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Claude Code
        run: npm install -g @anthropic-ai/claude-code

      - name: Install Dispatch
        run: npm install -g dispatch-ai

      - name: Run Dispatch
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          dispatch run \\
            --max-issues \${{ github.event.inputs.max_issues || '${maxIssues}' }} \\${draft ? "\n            --draft \\" : ""}${labels.length > 0 ? `\n            --label ${labels.join(" ")} \\` : ""}
            \${{ github.event.inputs.dry_run == 'true' && '--dry-run' || '' }}

      - name: Upload run logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dispatch-logs-\${{ github.run_id }}
          path: .dispatch/
          retention-days: 30
`;

function parseCronTime(time: string): string {
  // Accept formats like "2am", "2:00", "02:00", "14:00", "2 AM", "midnight"
  const normalized = time.toLowerCase().trim();

  if (normalized === "midnight") return "0 0 * * *";
  if (normalized === "noon") return "0 12 * * *";

  // Try HH:MM format
  const hhmmMatch = normalized.match(/^(\d{1,2}):(\d{2})$/);
  if (hhmmMatch) {
    const hour = parseInt(hhmmMatch[1], 10);
    const minute = parseInt(hhmmMatch[2], 10);
    if (hour >= 0 && hour <= 23 && minute >= 0 && minute <= 59) {
      return `${minute} ${hour} * * *`;
    }
  }

  // Try "2am", "2 am", "2pm", "2 pm" format
  const ampmMatch = normalized.match(/^(\d{1,2})\s*(am|pm)$/);
  if (ampmMatch) {
    let hour = parseInt(ampmMatch[1], 10);
    const period = ampmMatch[2];
    if (period === "pm" && hour !== 12) hour += 12;
    if (period === "am" && hour === 12) hour = 0;
    if (hour >= 0 && hour <= 23) {
      return `0 ${hour} * * *`;
    }
  }

  // Default: 2 AM UTC
  return "0 2 * * *";
}

export function registerScheduleCommand(program: Command) {
  program
    .command("schedule")
    .description("Generate a GitHub Actions workflow for nightly scheduled runs")
    .option("--time <time>", "Time to run in UTC (e.g., '2am', '03:00', 'midnight')", "2am")
    .option("--max-issues <n>", "Max issues per nightly run", parseInt)
    .option("--draft", "Create PRs as drafts")
    .option("--label <labels...>", "Only process issues with these labels")
    .option("--cron <expression>", "Custom cron expression (overrides --time)")
    .option("--stdout", "Print workflow to stdout instead of writing file")
    .action(async (options) => {
      try {
        const cwd = process.cwd();

        // Verify we're in a git repo
        let owner: string, repo: string;
        try {
          ({ owner, repo } = await getRepoInfo(cwd));
        } catch {
          log.error("Not in a Git repository with a GitHub remote.");
          log.info("Run this command from the root of your GitHub repository.");
          process.exit(1);
          return;
        }

        log.header("Dispatch Schedule Setup");
        log.info(`Repository: ${chalk.bold(`${owner}/${repo}`)}`);

        const cronSchedule = options.cron || parseCronTime(options.time);
        const maxIssues = options.maxIssues || 10;
        const draft = options.draft || false;
        const labels = options.label || [];

        const workflow = WORKFLOW_TEMPLATE(cronSchedule, maxIssues, draft, labels);

        if (options.stdout) {
          console.log(workflow);
          return;
        }

        // Write the workflow file
        const workflowDir = join(cwd, ".github", "workflows");
        const workflowPath = join(workflowDir, "dispatch-nightly.yml");

        await mkdir(workflowDir, { recursive: true });

        // Check if file already exists
        let exists = false;
        try {
          await access(workflowPath);
          exists = true;
        } catch {
          // doesn't exist — good
        }

        await writeFile(workflowPath, workflow, "utf-8");

        console.log();

        if (exists) {
          log.warn(`Updated existing workflow: ${chalk.bold(workflowPath)}`);
        } else {
          log.success(`Created workflow: ${chalk.bold(workflowPath)}`);
        }

        console.log();
        console.log(chalk.bold("  Schedule:"));
        console.log(chalk.gray(`    Cron: ${cronSchedule}`));
        console.log(chalk.gray(`    Time: ${options.time || "2:00 AM"} UTC (daily)`));
        console.log(chalk.gray(`    Max issues: ${maxIssues}`));
        if (labels.length > 0) {
          console.log(chalk.gray(`    Labels: ${labels.join(", ")}`));
        }
        console.log();
        console.log(chalk.bold("  Required Secrets:"));
        console.log(chalk.gray(`    ${chalk.yellow("ANTHROPIC_API_KEY")}  — Your Anthropic API key`));
        console.log(chalk.gray(`    ${chalk.yellow("GITHUB_TOKEN")}       — Auto-provided by GitHub Actions`));
        console.log();
        console.log(chalk.bold("  Next Steps:"));
        console.log(chalk.gray(`    1. Add your Anthropic API key as a repository secret:`));
        console.log(chalk.gray(`       ${chalk.yellow(`https://github.com/${owner}/${repo}/settings/secrets/actions`)}`));
        console.log(chalk.gray(`    2. Commit and push the workflow file:`));
        console.log(chalk.gray(`       ${chalk.yellow("git add .github/workflows/dispatch-nightly.yml")}`));
        console.log(chalk.gray(`       ${chalk.yellow('git commit -m "Add dispatch nightly workflow"')}`));
        console.log(chalk.gray(`       ${chalk.yellow("git push")}`));
        console.log(chalk.gray(`    3. Optionally trigger a manual run from the Actions tab`));
        console.log();
        console.log(chalk.bold("  Alternative — Local cron job:"));
        console.log(chalk.gray(`    Add this to your crontab (${chalk.yellow("crontab -e")}):`));
        console.log(chalk.gray(`    ${chalk.yellow(`${cronSchedule} cd ${cwd} && dispatch run >> /tmp/dispatch.log 2>&1`)}`));
        console.log();
      } catch (err) {
        log.error(`Schedule setup failed: ${err instanceof Error ? err.message : err}`);
        process.exit(1);
      }
    });
}
